private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"  # funded anvil test account, used for broadcasting txns. see https://github.com/foundry-rs/foundry/tree/master/anvil

node_endpoint: "http://localhost:8545"
quay_endpoint: "https://localhost:8000"
settlement_contract: "0x7513F78472606625A9B505912e3C80762f6C9Efb"

# Approve the example taker tokens for spending by the settlement contract
approve_tokens: false

# This is an optional setting, if not given a keystore will need to be provided on startup
# keystore: "/path/to/keystore.ks"

# These are an optional setting, if not given the default location of /etc/ssl/cert.pem will be used for the root
# certificate authority for TLS certificate validation
ca_root: "certs/rootCA.crt"
domain_name: "localhost.com"